---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Необходимо конкретизировать требования по производительности, узнать примерную необходимую нагрузку с учётом работы, планируемой маркетингом
  - Необходимо определить целевую аудиторию для которой будет разработан интернет-магазин и провести тестирование локализации
  - Сайт должен соответствовать требованиям законодательства стран целевой аудитории
  - Необходимо проработать момент как пользователь может получить помощь в случае проблем, как будет осуществляться поддержка клиентов
  - Поле поиска должно обеспечивать нахождение всех товаров в магазине, соответствующих введённому неполному названию товара / товаров
  - При вводе несуществующего названия товара в поле поиска показывать пользователю сообщение: "Nothing found!"
  - Пользователь должен иметь возможность вставлять скопированный текст в поле поиска
  - Вставленный в поле поиска текст должен корректно обрабатываться: в случае, когда вставленный текст соответствует названию товара / товаров - должны отобразиться соответствующие товары; в случае, когда вставленный текст не соответствует названию товара / товаров -  показывать пользователю сообщение: "Nothing found!"
  - Если пользователь, не выбрав ни одной категории, нажал ЛКМ или ПКМ вне списка с категориями, то список с категориями должен закрываться
  - Если пользователь выбрал категорию - список с категориями должен закрываться
  - Выбранная категория должна отображаться под Category
  - При выборе (включении) чек-бокса должна срабатывать подсветка по краям чек-бокса
  - При отключении чек-бокса с брэндом убирать подсветку чек-бокса
  - Чек-бокс "In Stock" должен быть включен по умолчанию
  - Кнопки Меньше и Больше должны отображаться при наведении на поля Price
  - Кнопки Меньше и Больше в полях Price: From и To, при нажатии на Меньше -  уменьшать число в поле на 1,  при нажатии на Больше - увеличивать число в поле на 1
  - При наведении курсора мыши на поля Price: From и To курсор по умолчанию должен меняться на текстовый курсор, при наведении на кнопки Больше, Меньше в полях From и To должен отображаться курсор по умолчанию
  - При нажатии на кнопку "Hexlet Store" в верхней панели осуществлять переход на текущую страницу с товарами
  - При нажатии на тег с категорией товара на странице товара с подробным описанием осуществлять переход на страницу с товарами, где будет выбрана категория, тег которой был указан в просматриваемом товаре
  - При нажатии на "Store" в верхней панели осуществлять переход на первую страницу с товарами, устанавливать значение для всех фильтров "по умолчанию"
  - На первой странице магазина должна быть только кнопка "Next", на страницах после первой должны быть кнопки "Previous" и "Next", на последней странице должна быть только кнопка "Previous"
  - Количество добавленных в корзину товаров должно отображаться в виде цифры сбоку от "Cart" в верхней панели
  - Кнопка Continue shopping при нажатии возвращает пользователя на страницу магазина, на которой он был до перехода в корзину
